//! CPAL-backed audio adapters for the Raspberry Pi client.
//!
//! Built-in tones are checked into `assets/` as FLAC files generated from
//! simple mathematical sine waves (no external samples or licenses). Keeping
//! the generated bytes in the tree avoids requiring a FLAC encoder binary at
//! Cargo build time while still letting the Pi build decode the exact assets it
//! will play.

// These pedantic lints fire across cpal/symphonia/flacenc glue code that is
// only compiled under the `audio` feature. The lints have been reviewed and
// the patterns (e.g. `f32 as i32` after `clamp` to `i16::MIN..=i16::MAX`) are
// intentional.
#![cfg_attr(
    feature = "audio",
    allow(
        clippy::cast_possible_truncation,
        clippy::cast_precision_loss,
        clippy::cast_sign_loss,
        clippy::similar_names,
        clippy::default_trait_access,
        clippy::needless_pass_by_value,
    )
)]

use std::collections::HashMap;
use std::sync::Arc;

use async_trait::async_trait;
use booth_hal::{
    AudioError, AudioRef, AudioSink, AudioSource, BuiltinTone, RecordingId, Storage, TelemetryEvent,
};
use tokio::sync::{Mutex, mpsc};

use crate::AudioConfig;

const DIAL_TONE_FLAC: &[u8] = include_bytes!("../assets/dial-tone.flac");
const BEEP_FLAC: &[u8] = include_bytes!("../assets/beep.flac");

/// Metadata for a finalized Pi recording.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RecordingHandle {
    /// Lowercase hexadecimal SHA-256 of the FLAC bytes.
    pub sha256: String,
    /// Final FLAC size on disk.
    pub size_bytes: u64,
    /// Captured duration in milliseconds.
    pub duration_ms: u64,
    /// Final filesystem path, normally `<recordings_dir>/<sha256>.flac`.
    pub path: String,
}

/// Return `true` when `candidate` matches the configured audio-device substring.
#[must_use]
pub fn device_name_matches(candidate: &str, configured_substring: Option<&str>) -> bool {
    configured_substring
        .map(str::trim)
        .filter(|needle| !needle.is_empty())
        .is_some_and(|needle| candidate.to_lowercase().contains(&needle.to_lowercase()))
}

/// Return the embedded FLAC bytes for a supported built-in tone.
pub fn embedded_tone_bytes(tone: BuiltinTone) -> Result<&'static [u8], AudioError> {
    match tone {
        BuiltinTone::DialTone => Ok(DIAL_TONE_FLAC),
        BuiltinTone::Beep => Ok(BEEP_FLAC),
        BuiltinTone::LineBusy => Err(AudioError::Unsupported(
            "line-busy tone is not bundled yet".into(),
        )),
    }
}

/// Return `true` when the bytes start with the FLAC stream marker.
#[must_use]
pub fn has_flac_stream_marker(bytes: &[u8]) -> bool {
    bytes.starts_with(b"fLaC")
}

/// Audio playback adapter for the Raspberry Pi.
pub struct PiAudioSink {
    config: AudioConfig,
    telemetry: Option<mpsc::Sender<TelemetryEvent>>,
    #[cfg(feature = "audio")]
    playback: Option<PlaybackTask>,
}

impl PiAudioSink {
    /// Create a sink without audio-level telemetry.
    #[must_use]
    pub fn new(config: AudioConfig) -> Self {
        Self::with_telemetry(config, None)
    }

    /// Create a sink that optionally publishes audio-level telemetry.
    #[must_use]
    pub fn with_telemetry(
        config: AudioConfig,
        telemetry: Option<mpsc::Sender<TelemetryEvent>>,
    ) -> Self {
        Self {
            config,
            telemetry,
            #[cfg(feature = "audio")]
            playback: None,
        }
    }

    #[cfg(not(feature = "audio"))]
    fn unsupported(&self) -> AudioError {
        let _ = (&self.config, &self.telemetry);
        AudioError::Unsupported("booth-pi audio requires the `audio` Cargo feature".into())
    }
}

#[async_trait]
impl AudioSink for PiAudioSink {
    async fn play(&mut self, source: AudioRef) -> Result<(), AudioError> {
        #[cfg(not(feature = "audio"))]
        {
            let _ = source;
            Err(self.unsupported())
        }

        #[cfg(feature = "audio")]
        {
            self.stop().await?;

            let playable = match source {
                AudioRef::Builtin(tone) => PlayableAudio {
                    samples: decode_audio_bytes(embedded_tone_bytes(tone)?)?,
                    repeat: tone == BuiltinTone::DialTone,
                },
                AudioRef::RemoteUrl(url) => {
                    use futures_util::StreamExt as _;

                    let response = reqwest::get(&url)
                        .await
                        .map_err(|err| AudioError::Source(format!("fetch {url}: {err}").into()))?;
                    let response = response
                        .error_for_status()
                        .map_err(|err| AudioError::Source(format!("fetch {url}: {err}").into()))?;

                    // Reject responses that advertise a body larger than the
                    // configured cap before buffering anything.
                    let max_bytes = self.config.max_audio_download_bytes;
                    if let Some(len) = response.content_length().filter(|&l| l > max_bytes) {
                        return Err(AudioError::Source(
                            format!(
                                "remote audio from {url} is {len} bytes, exceeds cap of {max_bytes}"
                            )
                            .into(),
                        ));
                    }

                    // Stream the body in chunks with a running size check so
                    // that responses without a Content-Length header are still
                    // bounded.
                    let mut buf = Vec::new();
                    let mut stream = response.bytes_stream();
                    while let Some(chunk) = stream.next().await {
                        let chunk = chunk.map_err(|err| {
                            AudioError::Source(
                                format!("read response body from {url}: {err}").into(),
                            )
                        })?;
                        if (buf.len() as u64) + (chunk.len() as u64) > max_bytes {
                            return Err(AudioError::Source(
                                format!("remote audio from {url} exceeds cap of {max_bytes} bytes")
                                    .into(),
                            ));
                        }
                        buf.extend_from_slice(&chunk);
                    }

                    PlayableAudio {
                        samples: decode_audio_bytes(&buf)?,
                        repeat: false,
                    }
                }
                AudioRef::LocalFile(path) => {
                    let max_bytes = self.config.max_audio_download_bytes;
                    let meta = std::fs::metadata(&path).map_err(|err| {
                        AudioError::Source(format!("stat audio file {path}: {err}").into())
                    })?;
                    if meta.len() > max_bytes {
                        return Err(AudioError::Source(
                            format!(
                                "local audio file {path} is {} bytes, exceeds cap of {max_bytes}",
                                meta.len()
                            )
                            .into(),
                        ));
                    }
                    let bytes = std::fs::read(&path).map_err(|err| {
                        AudioError::Source(format!("read audio file {path}: {err}").into())
                    })?;
                    PlayableAudio {
                        samples: decode_audio_bytes(&bytes)?,
                        repeat: false,
                    }
                }
            };

            let cancel = Arc::new(std::sync::atomic::AtomicBool::new(false));
            let task_cancel = Arc::clone(&cancel);
            let config = self.config.clone();
            let telemetry = self.telemetry.clone();
            let handle = tokio::task::spawn_blocking(move || {
                play_blocking(config, telemetry, playable, task_cancel)
            });
            self.playback = Some(PlaybackTask { cancel, handle });
            Ok(())
        }
    }

    async fn stop(&mut self) -> Result<(), AudioError> {
        #[cfg(not(feature = "audio"))]
        {
            Err(self.unsupported())
        }

        #[cfg(feature = "audio")]
        {
            if let Some(task) = self.playback.take() {
                task.cancel.store(true, std::sync::atomic::Ordering::SeqCst);
                join_audio_task(task.handle).await?;
            }
            Ok(())
        }
    }

    async fn wait_for_end(&mut self) -> Result<(), AudioError> {
        #[cfg(not(feature = "audio"))]
        {
            Err(self.unsupported())
        }

        #[cfg(feature = "audio")]
        {
            if let Some(task) = self.playback.take() {
                join_audio_task(task.handle).await?;
            }
            Ok(())
        }
    }
}

/// Audio capture adapter for the Raspberry Pi.
pub struct PiAudioSource {
    config: AudioConfig,
    storage: Arc<dyn Storage>,
    telemetry: Option<mpsc::Sender<TelemetryEvent>>,
    finished: Mutex<HashMap<RecordingId, RecordingHandle>>,
    #[cfg(feature = "audio")]
    recording: Option<RecordingTask>,
}

#[cfg_attr(
    not(feature = "pi"),
    allow(clippy::needless_return, clippy::unused_async)
)]
impl PiAudioSource {
    /// Create a source without audio-level telemetry.
    #[must_use]
    pub fn new(config: AudioConfig, storage: Arc<dyn Storage>) -> Self {
        Self::with_telemetry(config, storage, None)
    }

    /// Create a source that optionally publishes audio-level telemetry.
    #[must_use]
    pub fn with_telemetry(
        config: AudioConfig,
        storage: Arc<dyn Storage>,
        telemetry: Option<mpsc::Sender<TelemetryEvent>>,
    ) -> Self {
        Self {
            config,
            storage,
            telemetry,
            finished: Mutex::new(HashMap::new()),
            #[cfg(feature = "audio")]
            recording: None,
        }
    }

    /// Begin a recording and return its provisional id.
    pub async fn start_recording(&mut self) -> Result<RecordingId, AudioError> {
        self.start().await
    }

    /// Stop the active recording and return its finalized handle.
    #[allow(
        clippy::unused_async,
        reason = "the pi implementation awaits the recording task; the host stub keeps the same API"
    )]
    pub async fn stop_recording(&mut self) -> Result<Option<RecordingHandle>, AudioError> {
        #[cfg(not(feature = "audio"))]
        {
            Err(self.unsupported())
        }

        #[cfg(feature = "audio")]
        {
            let Some(task) = self.recording.take() else {
                return Ok(None);
            };
            task.cancel.store(true, std::sync::atomic::Ordering::SeqCst);
            let handle = join_recording_task(task.handle).await?;
            persist_recording_handle(&self.storage, &handle).await;
            self.finished
                .lock()
                .await
                .insert(handle.sha256.clone(), handle.clone());
            Ok(Some(handle))
        }
    }

    #[cfg(not(feature = "audio"))]
    fn unsupported(&self) -> AudioError {
        let _ = (&self.config, &self.storage, &self.telemetry, &self.finished);
        AudioError::Unsupported("booth-pi audio requires the `audio` Cargo feature".into())
    }
}

#[async_trait]
impl AudioSource for PiAudioSource {
    async fn start(&mut self) -> Result<RecordingId, AudioError> {
        #[cfg(not(feature = "audio"))]
        {
            Err(self.unsupported())
        }

        #[cfg(feature = "audio")]
        {
            if self.recording.is_some() {
                return Err(AudioError::Device("recording already in progress".into()));
            }
            let provisional_id = provisional_recording_id();
            let cancel = Arc::new(std::sync::atomic::AtomicBool::new(false));
            let task_cancel = Arc::clone(&cancel);
            let config = self.config.clone();
            let telemetry = self.telemetry.clone();
            let handle = tokio::task::spawn_blocking(move || {
                record_blocking(config, telemetry, task_cancel)
            });
            self.recording = Some(RecordingTask { cancel, handle });
            Ok(provisional_id)
        }
    }

    async fn stop(&mut self) -> Result<Option<RecordingId>, AudioError> {
        Ok(self
            .stop_recording()
            .await?
            .map(|handle| handle.sha256.clone()))
    }

    async fn path_of(&self, id: &RecordingId) -> Result<String, AudioError> {
        #[cfg(not(feature = "audio"))]
        {
            let _ = id;
            Err(self.unsupported())
        }

        #[cfg(feature = "audio")]
        {
            if let Some(handle) = self.finished.lock().await.get(id) {
                return Ok(handle.path.clone());
            }
            let key = recording_path_key(id);
            let Some(bytes) = self.storage.get(&key).await.map_err(|err| {
                AudioError::Io(format!("read recording path metadata {key}: {err}").into())
            })?
            else {
                return Err(AudioError::Source(
                    format!("unknown recording id {id}").into(),
                ));
            };
            String::from_utf8(bytes).map_err(|err| {
                AudioError::Io(
                    format!("recording path metadata for {id} is not utf-8: {err}").into(),
                )
            })
        }
    }

    async fn cleanup_recording(&self, id: &RecordingId) -> Result<(), AudioError> {
        #[cfg(not(feature = "audio"))]
        {
            let _ = id;
            Ok(())
        }

        #[cfg(feature = "audio")]
        {
            self.finished.lock().await.remove(id);
            let key = recording_path_key(id);
            self.storage.delete(&key).await.map_err(|err| {
                AudioError::Io(format!("delete recording path metadata {key}: {err}").into())
            })?;
            Ok(())
        }
    }
}

#[cfg(feature = "audio")]
struct PlaybackTask {
    cancel: Arc<std::sync::atomic::AtomicBool>,
    handle: tokio::task::JoinHandle<Result<(), AudioError>>,
}

#[cfg(feature = "audio")]
struct RecordingTask {
    cancel: Arc<std::sync::atomic::AtomicBool>,
    handle: tokio::task::JoinHandle<Result<RecordingHandle, AudioError>>,
}

#[cfg(feature = "audio")]
struct PlayableAudio {
    samples: DecodedAudio,
    repeat: bool,
}

#[cfg(feature = "audio")]
struct DecodedAudio {
    samples: Vec<f32>,
    sample_rate_hz: u32,
}

#[cfg(feature = "audio")]
async fn join_audio_task(
    handle: tokio::task::JoinHandle<Result<(), AudioError>>,
) -> Result<(), AudioError> {
    handle
        .await
        .map_err(|err| AudioError::Device(format!("audio playback task failed: {err}").into()))?
}

#[cfg(feature = "audio")]
async fn join_recording_task(
    handle: tokio::task::JoinHandle<Result<RecordingHandle, AudioError>>,
) -> Result<RecordingHandle, AudioError> {
    handle
        .await
        .map_err(|err| AudioError::Device(format!("audio recording task failed: {err}").into()))?
}

#[cfg(feature = "audio")]
async fn persist_recording_handle(storage: &Arc<dyn Storage>, handle: &RecordingHandle) {
    let key = recording_path_key(&handle.sha256);
    if let Err(err) = storage.set(&key, handle.path.as_bytes()).await {
        tracing::warn!(%key, %err, "failed to persist recording path metadata");
    }
}

#[cfg(feature = "audio")]
fn recording_path_key(id: &str) -> String {
    format!("recording:{id}:path")
}

#[cfg(feature = "audio")]
fn provisional_recording_id() -> String {
    format!("recording-{}", monotonic_ns())
}

#[cfg(feature = "audio")]
fn monotonic_ns() -> u64 {
    static START: std::sync::OnceLock<std::time::Instant> = std::sync::OnceLock::new();
    let nanos = START
        .get_or_init(std::time::Instant::now)
        .elapsed()
        .as_nanos();
    u64::try_from(nanos).unwrap_or(u64::MAX)
}

#[cfg(feature = "audio")]
fn decode_audio_bytes(bytes: &[u8]) -> Result<DecodedAudio, AudioError> {
    use std::io::{Cursor, ErrorKind};

    use symphonia::core::audio::SampleBuffer;
    use symphonia::core::codecs::DecoderOptions;
    use symphonia::core::errors::Error as SymphoniaError;
    use symphonia::core::formats::FormatOptions;
    use symphonia::core::io::MediaSourceStream;
    use symphonia::core::meta::MetadataOptions;
    use symphonia::core::probe::Hint;

    let cursor = Cursor::new(bytes.to_vec());
    let media_source = MediaSourceStream::new(Box::new(cursor), Default::default());
    let probed = symphonia::default::get_probe()
        .format(
            &Hint::new(),
            media_source,
            &FormatOptions::default(),
            &MetadataOptions::default(),
        )
        .map_err(|err| AudioError::Codec(format!("probe audio stream: {err}").into()))?;
    let mut format = probed.format;
    let track = format
        .default_track()
        .ok_or_else(|| AudioError::Codec("audio stream has no default track".into()))?;
    let track_id = track.id;
    let mut decoder = symphonia::default::get_codecs()
        .make(&track.codec_params, &DecoderOptions::default())
        .map_err(|err| AudioError::Codec(format!("create decoder: {err}").into()))?;

    let mut samples = Vec::new();
    let mut sample_rate_hz = track.codec_params.sample_rate.unwrap_or(48_000);

    loop {
        let packet = match format.next_packet() {
            Ok(packet) => packet,
            Err(SymphoniaError::IoError(err)) if err.kind() == ErrorKind::UnexpectedEof => break,
            Err(err) => {
                return Err(AudioError::Codec(
                    format!("read audio packet: {err}").into(),
                ));
            }
        };
        if packet.track_id() != track_id {
            continue;
        }
        let decoded = match decoder.decode(&packet) {
            Ok(decoded) => decoded,
            Err(SymphoniaError::ResetRequired) => {
                decoder.reset();
                continue;
            }
            Err(err) => {
                return Err(AudioError::Codec(
                    format!("decode audio packet: {err}").into(),
                ));
            }
        };
        sample_rate_hz = decoded.spec().rate;
        let spec = *decoded.spec();
        let mut buffer = SampleBuffer::<f32>::new(decoded.capacity() as u64, spec);
        buffer.copy_interleaved_ref(decoded);
        let channels = spec.channels.count().max(1);
        if channels == 1 {
            samples.extend_from_slice(buffer.samples());
        } else {
            samples.extend(
                buffer
                    .samples()
                    .chunks(channels)
                    .map(|frame| frame.iter().copied().sum::<f32>() / frame.len() as f32),
            );
        }
    }

    if samples.is_empty() {
        return Err(AudioError::Codec(
            "audio stream decoded to zero samples".into(),
        ));
    }

    Ok(DecodedAudio {
        samples,
        sample_rate_hz,
    })
}

#[cfg(feature = "audio")]
fn play_blocking(
    config: AudioConfig,
    telemetry: Option<mpsc::Sender<TelemetryEvent>>,
    playable: PlayableAudio,
    cancel: Arc<std::sync::atomic::AtomicBool>,
) -> Result<(), AudioError> {
    use std::sync::mpsc as std_mpsc;
    use std::time::Duration;

    use cpal::traits::{DeviceTrait, StreamTrait};

    let host = cpal::default_host();
    let device = select_output_device(&host, config.device_substring.as_deref())?;
    let supported = device
        .default_output_config()
        .map_err(|err| AudioError::Device(format!("default output config: {err}").into()))?;
    let sample_format = supported.sample_format();
    let stream_config = cpal::StreamConfig {
        channels: config.channels,
        sample_rate: cpal::SampleRate(playable.samples.sample_rate_hz),
        buffer_size: cpal::BufferSize::Default,
    };
    let samples = Arc::new(playable.samples.samples);
    let (done_tx, done_rx) = std_mpsc::sync_channel(1);
    let done = Arc::new(std::sync::atomic::AtomicBool::new(false));
    let err_fn = |err| tracing::warn!(%err, "output audio stream error");

    let stream = match sample_format {
        cpal::SampleFormat::F32 => build_output_stream::<f32, _>(
            &device,
            &stream_config,
            Arc::clone(&samples),
            playable.repeat,
            Arc::clone(&cancel),
            Arc::clone(&done),
            done_tx.clone(),
            telemetry,
            err_fn,
        )
        .map_err(|err| AudioError::Device(format!("build output stream: {err}").into()))?,
        cpal::SampleFormat::I16 => build_output_stream::<i16, _>(
            &device,
            &stream_config,
            Arc::clone(&samples),
            playable.repeat,
            Arc::clone(&cancel),
            Arc::clone(&done),
            done_tx.clone(),
            telemetry,
            err_fn,
        )
        .map_err(|err| AudioError::Device(format!("build output stream: {err}").into()))?,
        cpal::SampleFormat::U16 => build_output_stream::<u16, _>(
            &device,
            &stream_config,
            Arc::clone(&samples),
            playable.repeat,
            Arc::clone(&cancel),
            Arc::clone(&done),
            done_tx,
            telemetry,
            err_fn,
        )
        .map_err(|err| AudioError::Device(format!("build output stream: {err}").into()))?,
        other => {
            return Err(AudioError::Device(
                format!("unsupported output sample format {other}").into(),
            ));
        }
    };

    stream
        .play()
        .map_err(|err| AudioError::Device(format!("start output stream: {err}").into()))?;

    loop {
        if cancel.load(std::sync::atomic::Ordering::SeqCst) {
            break;
        }
        if done_rx.recv_timeout(Duration::from_millis(50)).is_ok() {
            break;
        }
    }
    drop(stream);
    Ok(())
}

#[cfg(feature = "audio")]
#[allow(
    clippy::too_many_arguments,
    reason = "CPAL callback construction needs shared playback state"
)]
fn build_output_stream<T, E>(
    device: &cpal::Device,
    config: &cpal::StreamConfig,
    samples: Arc<Vec<f32>>,
    repeat: bool,
    cancel: Arc<std::sync::atomic::AtomicBool>,
    done: Arc<std::sync::atomic::AtomicBool>,
    done_tx: std::sync::mpsc::SyncSender<()>,
    telemetry: Option<mpsc::Sender<TelemetryEvent>>,
    err_fn: E,
) -> Result<cpal::Stream, cpal::BuildStreamError>
where
    T: cpal::Sample + cpal::SizedSample + cpal::FromSample<f32>,
    E: FnMut(cpal::StreamError) + Send + 'static,
{
    use cpal::FromSample;
    use cpal::traits::DeviceTrait;

    let mut cursor = 0usize;
    let mut meter = LevelMeter::new(
        booth_hal::AudioChannel::Output,
        config.sample_rate.0,
        telemetry,
    );
    device.build_output_stream(
        config,
        move |data: &mut [T], _| {
            for sample in data {
                let value = if cancel.load(std::sync::atomic::Ordering::SeqCst)
                    || done.load(std::sync::atomic::Ordering::SeqCst)
                {
                    0.0
                } else if cursor < samples.len() {
                    let value = samples[cursor];
                    cursor = cursor.saturating_add(1);
                    value
                } else if repeat {
                    cursor = 0;
                    samples.get(cursor).copied().unwrap_or(0.0)
                } else {
                    done.store(true, std::sync::atomic::Ordering::SeqCst);
                    let _ = done_tx.try_send(());
                    0.0
                };
                meter.observe(value);
                *sample = <T as FromSample<f32>>::from_sample_(value.clamp(-1.0, 1.0));
            }
        },
        err_fn,
        None,
    )
}

#[cfg(feature = "audio")]
fn record_blocking(
    config: AudioConfig,
    telemetry: Option<mpsc::Sender<TelemetryEvent>>,
    cancel: Arc<std::sync::atomic::AtomicBool>,
) -> Result<RecordingHandle, AudioError> {
    use std::time::{Duration, Instant};

    use cpal::traits::{DeviceTrait, StreamTrait};

    let host = cpal::default_host();
    let device = select_input_device(&host, config.device_substring.as_deref())?;
    let supported = device
        .default_input_config()
        .map_err(|err| AudioError::Device(format!("default input config: {err}").into()))?;
    let sample_format = supported.sample_format();
    let stream_config = cpal::StreamConfig {
        channels: config.channels,
        sample_rate: cpal::SampleRate(config.sample_rate_hz),
        buffer_size: cpal::BufferSize::Default,
    };
    let samples = Arc::new(std::sync::Mutex::new(Vec::<i32>::new()));
    let max_samples = usize::try_from(config.sample_rate_hz)
        .unwrap_or(48_000)
        .saturating_mul(usize::from(config.channels))
        .saturating_mul(usize::try_from(config.max_recording_secs).unwrap_or(60));
    let err_fn = |err| tracing::warn!(%err, "input audio stream error");

    let stream = match sample_format {
        cpal::SampleFormat::F32 => build_input_stream::<f32, _>(
            &device,
            &stream_config,
            Arc::clone(&samples),
            max_samples,
            Arc::clone(&cancel),
            telemetry,
            err_fn,
        )
        .map_err(|err| AudioError::Device(format!("build input stream: {err}").into()))?,
        cpal::SampleFormat::I16 => build_input_stream::<i16, _>(
            &device,
            &stream_config,
            Arc::clone(&samples),
            max_samples,
            Arc::clone(&cancel),
            telemetry,
            err_fn,
        )
        .map_err(|err| AudioError::Device(format!("build input stream: {err}").into()))?,
        cpal::SampleFormat::U16 => build_input_stream::<u16, _>(
            &device,
            &stream_config,
            Arc::clone(&samples),
            max_samples,
            Arc::clone(&cancel),
            telemetry,
            err_fn,
        )
        .map_err(|err| AudioError::Device(format!("build input stream: {err}").into()))?,
        other => {
            return Err(AudioError::Device(
                format!("unsupported input sample format {other}").into(),
            ));
        }
    };

    stream
        .play()
        .map_err(|err| AudioError::Device(format!("start input stream: {err}").into()))?;
    let started = Instant::now();
    let max_duration = Duration::from_secs(u64::from(config.max_recording_secs));
    while !cancel.load(std::sync::atomic::Ordering::SeqCst) && started.elapsed() < max_duration {
        std::thread::sleep(Duration::from_millis(25));
    }
    drop(stream);

    let samples = Arc::try_unwrap(samples)
        .map_err(|_| AudioError::Device("recording samples still shared".into()))?
        .into_inner()
        .map_err(|err| {
            AudioError::Device(format!("recording samples lock poisoned: {err}").into())
        })?;
    finalize_recording(&config, &samples)
}

#[cfg(feature = "audio")]
fn build_input_stream<T, E>(
    device: &cpal::Device,
    config: &cpal::StreamConfig,
    samples: Arc<std::sync::Mutex<Vec<i32>>>,
    max_samples: usize,
    cancel: Arc<std::sync::atomic::AtomicBool>,
    telemetry: Option<mpsc::Sender<TelemetryEvent>>,
    err_fn: E,
) -> Result<cpal::Stream, cpal::BuildStreamError>
where
    T: cpal::Sample + cpal::SizedSample,
    f32: cpal::FromSample<T>,
    E: FnMut(cpal::StreamError) + Send + 'static,
{
    use cpal::FromSample;
    use cpal::traits::DeviceTrait;

    let mut meter = LevelMeter::new(
        booth_hal::AudioChannel::Input,
        config.sample_rate.0,
        telemetry,
    );
    device.build_input_stream(
        config,
        move |data: &[T], _| {
            if cancel.load(std::sync::atomic::Ordering::SeqCst) {
                return;
            }
            let Ok(mut sink) = samples.lock() else {
                tracing::warn!("recording sample buffer lock poisoned");
                cancel.store(true, std::sync::atomic::Ordering::SeqCst);
                return;
            };
            for sample in data {
                let value = <f32 as FromSample<T>>::from_sample_(*sample).clamp(-1.0, 1.0);
                meter.observe(value);
                let scaled = (value * f32::from(i16::MAX)).round();
                sink.push(scaled.clamp(f32::from(i16::MIN), f32::from(i16::MAX)) as i32);
                if sink.len() >= max_samples {
                    cancel.store(true, std::sync::atomic::Ordering::SeqCst);
                    break;
                }
            }
        },
        err_fn,
        None,
    )
}

#[cfg(feature = "audio")]
fn finalize_recording(
    config: &AudioConfig,
    samples: &[i32],
) -> Result<RecordingHandle, AudioError> {
    use flacenc::component::BitRepr;
    use flacenc::error::Verify;
    std::fs::create_dir_all(&config.recordings_dir).map_err(|err| {
        AudioError::Io(format!("create recordings dir {}: {err}", config.recordings_dir).into())
    })?;
    let encoder = flacenc::config::Encoder::default()
        .into_verified()
        .map_err(|(_, err)| {
            AudioError::Codec(format!("verify FLAC encoder config: {err}").into())
        })?;
    let source = flacenc::source::MemSource::from_samples(
        samples,
        usize::from(config.channels),
        16,
        config.sample_rate_hz as usize,
    );
    let stream = flacenc::encode_with_fixed_block_size(&encoder, source, encoder.block_size)
        .map_err(|err| AudioError::Codec(format!("encode FLAC recording: {err:?}").into()))?;
    let mut sink = flacenc::bitsink::ByteSink::new();
    stream
        .write(&mut sink)
        .map_err(|err| AudioError::Codec(format!("serialize FLAC recording: {err}").into()))?;
    let encoded = sink.as_slice();
    let sha256 = hex_sha256(encoded);
    let temp_path = std::path::Path::new(&config.recordings_dir).join(format!(
        ".recording-{}-{}.flac",
        std::process::id(),
        monotonic_ns()
    ));
    let final_path = std::path::Path::new(&config.recordings_dir).join(format!("{sha256}.flac"));
    std::fs::write(&temp_path, encoded).map_err(|err| {
        AudioError::Io(format!("write temp recording {}: {err}", temp_path.display()).into())
    })?;
    std::fs::rename(&temp_path, &final_path).map_err(|err| {
        AudioError::Io(
            format!(
                "rename recording {} to {}: {err}",
                temp_path.display(),
                final_path.display()
            )
            .into(),
        )
    })?;
    let size_bytes = u64::try_from(encoded.len()).unwrap_or(u64::MAX);
    let frames =
        u64::try_from(samples.len()).unwrap_or(u64::MAX) / u64::from(config.channels.max(1));
    let duration_ms = frames.saturating_mul(1_000) / u64::from(config.sample_rate_hz.max(1));

    Ok(RecordingHandle {
        sha256,
        size_bytes,
        duration_ms,
        path: final_path.to_string_lossy().into_owned(),
    })
}

#[cfg(feature = "audio")]
fn hex_sha256(bytes: &[u8]) -> String {
    use sha2::{Digest, Sha256};

    let digest = Sha256::digest(bytes);
    let mut out = String::with_capacity(digest.len() * 2);
    for byte in digest {
        use std::fmt::Write as _;
        let _ = write!(&mut out, "{byte:02x}");
    }
    out
}

#[cfg(feature = "audio")]
fn select_output_device(
    host: &cpal::Host,
    substring: Option<&str>,
) -> Result<cpal::Device, AudioError> {
    use cpal::traits::{DeviceTrait, HostTrait};

    if let Some(needle) = substring.filter(|value| !value.trim().is_empty()) {
        let devices = host.output_devices().map_err(|err| {
            AudioError::NoDevice(format!("enumerate output devices: {err}").into())
        })?;
        for device in devices {
            let name = device
                .name()
                .unwrap_or_else(|err| format!("<unnameable: {err}>"));
            if device_name_matches(&name, Some(needle)) {
                return Ok(device);
            }
        }
        tracing::warn!(%needle, "configured output device not found; falling back to default");
    }
    host.default_output_device()
        .ok_or_else(|| AudioError::NoDevice("no default output device".into()))
}

#[cfg(feature = "audio")]
fn select_input_device(
    host: &cpal::Host,
    substring: Option<&str>,
) -> Result<cpal::Device, AudioError> {
    use cpal::traits::{DeviceTrait, HostTrait};

    if let Some(needle) = substring.filter(|value| !value.trim().is_empty()) {
        let devices = host.input_devices().map_err(|err| {
            AudioError::NoDevice(format!("enumerate input devices: {err}").into())
        })?;
        for device in devices {
            let name = device
                .name()
                .unwrap_or_else(|err| format!("<unnameable: {err}>"));
            if device_name_matches(&name, Some(needle)) {
                return Ok(device);
            }
        }
        tracing::warn!(%needle, "configured input device not found; falling back to default");
    }
    host.default_input_device()
        .ok_or_else(|| AudioError::NoDevice("no default input device".into()))
}

#[cfg(feature = "audio")]
struct LevelMeter {
    channel: booth_hal::AudioChannel,
    telemetry: Option<mpsc::Sender<TelemetryEvent>>,
    sample_rate_hz: u32,
    observed: u32,
    sum_squares: f32,
    peak: f32,
}

#[cfg(feature = "audio")]
impl LevelMeter {
    fn new(
        channel: booth_hal::AudioChannel,
        sample_rate_hz: u32,
        telemetry: Option<mpsc::Sender<TelemetryEvent>>,
    ) -> Self {
        Self {
            channel,
            telemetry,
            sample_rate_hz,
            observed: 0,
            sum_squares: 0.0,
            peak: 0.0,
        }
    }

    fn observe(&mut self, sample: f32) {
        let magnitude = sample.abs().clamp(0.0, 1.0);
        self.peak = self.peak.max(magnitude);
        self.sum_squares += magnitude * magnitude;
        self.observed = self.observed.saturating_add(1);
        let interval = (self.sample_rate_hz / 20).max(1);
        if self.observed >= interval {
            self.flush();
        }
    }

    fn flush(&mut self) {
        let rms = if self.observed == 0 {
            0.0
        } else {
            (self.sum_squares / self.observed as f32).sqrt()
        };
        if let Some(tx) = &self.telemetry {
            let _ = tx.try_send(TelemetryEvent::AudioLevel(booth_hal::AudioLevel {
                channel: self.channel,
                peak: self.peak,
                rms,
                at_monotonic_ns: monotonic_ns(),
            }));
        }
        self.observed = 0;
        self.sum_squares = 0.0;
        self.peak = 0.0;
    }
}

#[cfg(all(test, feature = "audio"))]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;
    use crate::AudioConfig;

    fn config_with_channels(channels: u16) -> AudioConfig {
        let dir = std::env::temp_dir().join(format!("booth-pi-test-{}", std::process::id()));
        AudioConfig {
            device_substring: None,
            sample_rate_hz: 48_000,
            channels,
            max_recording_secs: 60,
            max_audio_download_bytes: 32 * 1024 * 1024,
            recordings_dir: dir.to_string_lossy().into_owned(),
        }
    }

    #[test]
    fn duration_mono_one_second() {
        let config = config_with_channels(1);
        // 48000 mono samples = 1 second
        let samples: Vec<i32> = vec![0; 48_000];
        let handle = finalize_recording(&config, &samples).expect("encode mono");
        assert_eq!(handle.duration_ms, 1_000);
        // Clean up
        let _ = std::fs::remove_file(&handle.path);
    }

    #[test]
    fn duration_stereo_one_second() {
        let config = config_with_channels(2);
        // 96000 interleaved stereo samples = 48000 frames = 1 second
        let samples: Vec<i32> = vec![0; 96_000];
        let handle = finalize_recording(&config, &samples).expect("encode stereo");
        assert_eq!(handle.duration_ms, 1_000);
        let _ = std::fs::remove_file(&handle.path);
    }

    #[test]
    fn duration_zero_channels_returns_codec_error() {
        // channels = 0 is nonsensical; the FLAC encoder rejects it before
        // we reach the duration arithmetic, so no divide-by-zero can occur.
        let config = config_with_channels(0);
        let samples: Vec<i32> = vec![0; 48_000];
        let err = finalize_recording(&config, &samples).unwrap_err();
        assert!(matches!(err, AudioError::Codec(_)));
    }

    #[tokio::test]
    async fn local_file_rejects_over_limit() {
        let dir = std::env::temp_dir().join(format!("booth-pi-cap-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let oversized = dir.join("oversized.flac");
        std::fs::write(&oversized, vec![0u8; 128]).unwrap();

        let config = AudioConfig {
            max_audio_download_bytes: 64, // 64 byte cap
            ..AudioConfig::default()
        };
        let mut sink = PiAudioSink::new(config);
        let result = sink
            .play(AudioRef::LocalFile(
                oversized.to_string_lossy().into_owned(),
            ))
            .await;

        let _ = std::fs::remove_dir_all(&dir);
        let err = result.unwrap_err();
        assert!(matches!(err, AudioError::Source(_)));
        assert!(
            err.to_string().contains("exceeds cap"),
            "unexpected error: {err}"
        );
    }
}
