#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1

start_service() {
  local enabled

  config_load telephone-booth-router-telemetry
  config_get_bool enabled main enabled 0
  [ "$enabled" -eq 1 ] || return 0

  procd_open_instance
  procd_set_param command /usr/bin/telephone-booth-router-telemetry-push
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_set_param respawn 3600 5 5
  procd_close_instance
}

service_triggers() {
  procd_add_reload_trigger telephone-booth-router-telemetry
}
