name: audit
on:
  push:
    branches: [rust-client, main]
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'crates/**/Cargo.toml'
      - '.github/workflows/audit.yml'
      - 'deny.toml'
  schedule:
    - cron: '17 6 * * 1'
  workflow_dispatch: {}

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: EmbarkStudios/cargo-deny-action@a531616d8ce3b9177443e48a1159bc945a099823 # v2
        with:
          command: check
          arguments: --all-features

  cargo-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: rustsec/audit-check@69366f33c96575abad1ee0dba8212993eecbe998 # v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
